" 配置vundle安装
set nocompatible " be iMproved
filetype off " required!


set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()

" let Vundle manage Vundle
" required!
"Bundle 'gmarik/vundle'
Plugin 'VundleVim/Vundle.vim'


" My Bundles here:
"
" original repos on github
" autocompletion
" Golang
Bundle 'fatih/vim-go'
Bundle 'davidhalter/jedi-vim'
" file tree
Bundle 'scrooloose/nerdtree'
" file search
Bundle 'kien/ctrlp.vim'
" file buffer search
"Bundle 'sjbach/lusty'
" git plugin
Bundle 'tpope/vim-fugitive'
" syntax checking plugin
Bundle 'vim-scripts/Syntastic'
"Bundle 'scrooloose/syntastic'
" comment code
Bundle 'scrooloose/nerdcommenter'
" tag of code
Bundle 'majutsushi/tagbar'
" search file
Bundle 'mileszs/ack.vim'

Bundle 'terryma/vim-multiple-cursors'
Bundle 'Lokaltog/vim-easymotion'

" 配色
Bundle 'altercation/vim-colors-solarized'
Bundle 'stephenmckinney/vim-solarized-powerline'

Bundle 'Lokaltog/vim-powerline'

" vim-scripts repos
Bundle 'L9'

" Mark down
Bundle 'plasticboy/vim-markdown'


" coffee-script
Bundle 'kchmck/vim-coffee-script'

" stylus
Bundle 'wavded/vim-stylus'

" non github repos
" Bundle 'git://git.wincent.com/command-t.git'

"
" 一些基本配置
"
call vundle#end()
filetype plugin indent on " required!
" Set to auto read when a file is changed from the outside
set autoread
let mapleader = ','
let g:mapleader = ','
let &termencoding=&encoding
set fileencodings=utf-8,gbk

let g:syntastic_python_checker_args = "--max-complexity 13 --ignore=E501"
let g:syntastic_always_populate_loc_list=1
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_echo_current_error=1
"let g:syntastic_auto_jump=1
"let g:syntastic_auto_loc_list=1

" Mark down
let g:vim_markdown_initial_foldlevel=1

" Ignore case when searching
set ignorecase smartcase
" Highlight search results
set hlsearch incsearch
" Use spaces instead of tabs
set expandtab smarttab shiftwidth=4 tabstop=4
"Always show current position
set ruler

set textwidth=79

"" Height of the command bar
set cmdheight=2
"禁止生成临时文件
set nobackup
set noswapfile

set wrap

vmap <c-c> "+y

" 状态栏配置
set laststatus =2 "always has status line

"colorscheme torte

"colorscheme desert
let g:molokai_original = 1
colorscheme desert

" comments in vim invisible when use molokai
"colorscheme molokai


"
"插件相关配置
"

" NERDTree=====
" au VimEnter * NERDTree
nmap <leader>nd :NERDTreeToggle<CR>
nmap <leader>tb :TagbarToggle<CR>
let NERDTreeWinSize=24
let NERDTreeIgnore=['\.pyc', '\.swp', '\~']
"tagbar window size
let g:tagbar_width = 25 
"switch window
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

"let g:Powerline_symbols = 'fancy'
let g:Powerline_colorscheme='solarized256_dark'
set t_Co=256 " 在终端启用256色

syntax enable
filetype plugin indent on

"
" Brief help
" :BundleList - list configured bundles
" :BundleInstall(!) - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!) - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
"
" Golang map
" au: automatic
" FileType go: golang file
" <leader> is defined previously: ','
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>ds <Plug>(go-def-split)
au FileType go nmap <leader>gd <Plug>(go-doc)
